name: Update Neovim Dependencies

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Install lazy.nvim
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/lazy/start
          git clone --filter=blob:none https://github.com/folke/lazy.nvim.git --branch=stable ~/.local/share/nvim/site/pack/lazy/start/lazy.nvim

      - name: Set up Neovim configuration
        run: |
          mkdir -p ~/.config
          ln -s $GITHUB_WORKSPACE ~/.config/nvim

      - name: Update dependencies
        run: |
          nvim --headless +qa
          nvim --headless "+Lazy! sync" +qa

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Check for changes and commit
        id: commit
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { execSync } = require('child_process');

            // Check if there are any changes
            try {
              execSync('git diff --exit-code');
              console.log('No changes detected');
              return false;
            } catch (error) {
              console.log('Changes detected');
            }

            // Stage changes
            execSync('git add .');

            // Commit changes
            const commitMessage = 'Auto-update Neovim dependencies';
            execSync(`git commit -m "${commitMessage}"`);

            // Push changes
            const { repo, owner } = context.repo;
            const push = await github.rest.git.createRef({
              owner,
              repo,
              ref: 'refs/heads/' + context.ref.replace('refs/heads/', ''),
              sha: execSync('git rev-parse HEAD').toString().trim()
            });

            console.log(`Changes pushed: ${push.data.url}`);
            return true;

      - name: Trigger dependent workflow
        if: success()
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          repository: rick-yao/dotfiles
          event-type: neovim-deps-updated
