name: Update Neovim Dependencies

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Install lazy.nvim
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/lazy/start
          git clone --filter=blob:none https://github.com/folke/lazy.nvim.git --branch=stable ~/.local/share/nvim/site/pack/lazy/start/lazy.nvim

      - name: Set up Neovim configuration
        run: |
          mkdir -p ~/.config
          ln -s $GITHUB_WORKSPACE ~/.config/nvim

      - name: Update dependencies
        run: |
          nvim --headless +qa
          nvim --headless "+Lazy! sync" +qa

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push if changes
        if: steps.git-check.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Auto-update Neovim dependencies"
          git push

      - name: Trigger dependent workflow
        if: success()
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          repository: rick-yao/dotfiles
          event-type: neovim-deps-updated
